### PR TITLE
a file with instruction to test check and build package and doc

### PR DESCRIPTION
**Pull request by philipperuiz**
this file describe the instructions to check tests (unit test) and build the package and to build the documentation.

### CODE REVIEW

**Comment by pveber** [comment]
Please move this contents to README.md and convert it to Markdown syntax.

**Comment by philipperuiz** [comment]
the readme file in markdown format contains the instruction part to check, test and build the package

**Comment by pveber** [comment]
was not rebased :o(((

**Comment by philipperuiz** [comment]
rebased

**Pull request merged**
