### PR TITLE
survData function

### PR DESCRIPTION
**Pull request by philipperuiz**
this function creats a survData object and calls the survDataCheck function. this function is associated with the survTransformData function

### CODE REVIEW

**Comment by philipperuiz** [comment]
the associated survTransformData function don't manage the missing replicate. (the survDataCheck function finds the missing replicate).

**Comment by pveber** [comment]
please rebase

**Comment by philipperuiz** [comment]
rebased

**Comment by pveber** [comment]
I'm affraid it's not (see the "network" graphics). Have you pushed your survData branch to your repo?

**Comment by philipperuiz** [comment]
superseeded by #11

**Pull request closed without merging**
